blogapp/urls.py
from django.urls import path 

from .views import blog, blog_single, post_switch

urlpatterns = [
    path('', blog, name='blog'),
    path('tag/<int:pk_tag>/', blog, name='tag'),
    path('author/<int:pk_auth>/', blog, name='author'),
    path('<slug:post_slug>/', blog_single, name='blog_single'),
    path('<int:pk>', post_switch, name='post_switch'),
 
]

eshopper/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

import mainapp.views as mainapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name = 'main'),
    path('', include('mainapp.urls')),
    path('blog/', include(('blogapp.urls', 'blogapp'), namespace='blog')),
    path('auth/', include(('authnapp.urls', 'authnapp'), namespace='auth')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.urls import reverse
from django.db.models.signals import post_save
from django.db import models
from django.db.models import Exists

from authnapp.models import CustomUser

from django.dispatch import receiver

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Author(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    facebook = models.CharField(max_length=64)
    twitter = models.CharField(max_length=64)
    google = models.CharField(max_length=64) 
    avatar = models.ImageField(upload_to="user_avatars", blank=True)

    @receiver(post_save, sender=CustomUser)
    def create_or_update_author(sender, instance, created, **kwargs):
        if created:
            Author.objects.create(user=instance)
        instance.author.save()

class Post(models.Model):
    
    title = models.CharField(max_length=64, unique=True )
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True, db_index=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    image = models.ImageField()
    likes = models.IntegerField(default=0)
    voice = models.IntegerField(default=0)
    slug = models.SlugField(max_length=250)
   

    class Meta:
        ordering = ['-publish']
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        
        return reverse("blog:blog_single", args=[self.slug])

    def count_full_stars(self):
        star_full = round(self.likes/self.voice)
        return range(star_full)

    def count_emp_stars(self):
        star_full = round(self.likes/self.voice)
        star_empty = 5 - star_full
        return range(star_empty)

   
class Comment(models.Model):
    
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    author =models.CharField(max_length=64)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='replies')

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f"{self.author}, ({self.post})"

blogapp/forms.py
from .models import Comment
from django import forms
from django.forms import TextInput, Textarea   


class HiddenForm(forms.Form):
    parent_id = forms.IntegerField(widget=forms.HiddenInput)

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['author'].widget = TextInput(attrs= {'placeholder':'write your name...'})
        self.fields['email'].widget = TextInput(attrs={'placeholder':'your email address...'})
        self.fields['body'].widget = Textarea(attrs={'placeholder':'write your commit...'})
        
    class Meta:
        model = Comment
        fields = ('author', 'email', 'body')

blogapp/views.py
from django.http import request
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.conf import settings
from django.urls import reverse
from .models import Post, Tag, Comment

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 
from .forms import CommentForm, HiddenForm

def blog(request, pk_tag=None, pk_auth=None):

    posts_list = Post.objects.all()
    if pk_tag is not None: 
        posts_list = Post.objects.filter(tags = pk_tag)
    if pk_auth is not None: 
        posts_list = Post.objects.filter(author = pk_auth)
       
    paginator = Paginator(posts_list, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    content = {'posts': posts, 'page':page, "media_url": settings.MEDIA_URL}
   
    return render(request, "blogapp/blog.html", content)


def save_id(request):
    parent_obj_id = int(request.GET['id'])
    print(parent_obj_id)


def blog_single(request, post_slug):
    
    post = get_object_or_404(Post, slug = post_slug) 
    post_next = Post.objects.filter(pk = post.pk + 1).exists()
    post_pre = Post.objects.filter(pk = post.pk - 1).exists()
    comments = Comment.objects.filter(active=True,parent__isnull=True, post = post.pk)
    count_comments = Comment.objects.filter(active=True,parent__isnull=True, post = post.pk).count()
     
    if  request.method == 'POST':
        comment_form = CommentForm(data=request.POST)  
        
        if comment_form.is_valid(): 
            parent_obj = None 
            try:  
               parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            if parent_id:
                parent_obj = Comment.objects.get(id=parent_id)
                if parent_obj:
                    replay_comment = comment_form.save(commit=False)
                    replay_comment.parent = parent_obj       
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form = CommentForm()
       
    content =  {'post':post, 
    "media_url": settings.MEDIA_URL, 
    'post_next':post_next, 
    'post_pre':post_pre, 
    'comments':comments,
    'comment_form':comment_form,
    'count_comments':count_comments,
    
    }
    return render(request, "blogapp/blog-single.html", content)

def post_switch(request, pk):  
    post = Post.objects.get(pk=pk)
    slug=post.slug
    url = reverse("blog:blog_single", args = (slug,))
    return HttpResponseRedirect(url)


 

blogapp/templates/blogapp/blog-single.html
{% extends "base.html" %}
{% load staticfiles %}


{% block title %} Blog Single {% endblock %}

{% block content %}    

								
						
						<div class="shipping text-center">
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div>
					</div>
				</div>
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">Latest From our Blog</h2>
						<div class="single-blog-post">
							<h3>{{ post.title }}</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> {{ post.author.user.first_name }} {{ post.author.user.last_name }}</li>
									<li><i class="fa fa-clock-o"></i> {{ post.publish.time }}</li>
									<li><i class="fa fa-calendar"></i> {{ post.publish.date }}</li>
								</ul>
								<span>
									{% for star in post.count_full_stars %}		
									<i class="fa fa-star"></i>
									{% endfor %}
									{% for star in post.count_emp_stars %}
									<i class="fa fa-star-o "></i>
									{% endfor %}

								</span>
							</div>
							<a href="">
								<img src="{{ media_url }}{{ post.image }}" alt="">
							</a>
							<p>
								{{ post.content|linebreaks  }}
							</p>
							<div class="pager-area">
								<ul class="pager pull-right">
								{% if post_pre %}
									<li><a href="{% url 'blog:post_switch' post.pk|add:'-1' %}">Pre</a></li>
								{% endif %}	
								{% if post_next %}
									<li><a href="{% url 'blog:post_switch' post.pk|add:'1' %}">Next</a></li>
								{% endif %}
								</ul>
							</div>
						</div>
					</div><!--/blog-post-area-->

					<div class="rating-area">
						<ul class="ratings">
							<li class="rate-this">Rate this item:</li>
							<li>
								{% for star in post.count_full_stars %}		
									<i class="fa fa-star color"></i>
									{% endfor %}
									{% for star in post.count_emp_stars %}
									<i class="fa fa-star-o "></i>
									{% endfor %}
							</li>
							<li class="color">({{ post.voice }} votes)</li>
						</ul>
						<ul class="tag">
							<li>TAG:</li>
							{% for tag in post.tags.all %}
								{% if forloop.counter < post.tags.count %}
								<li> <a class="color" href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a><span>/</span></li>
								{% else %}
								<li> <a class="color" href="{% url 'blog:tag' tag.pk %}">{{ tag }}</a></li>
								{% endif %}
							{% endfor %}							
						</ul>
					</div><!--/rating-area-->

					<div class="socials-share">
						<a href=""><img src="{% static 'images/blog/socials.png' %}" alt=""></a>
					</div><!--/socials-share-->

					<div class="media commnets">
						<a class="pull-left" href="#">
							<img class="media-object" src="{{ media_url }}{{ post.author.avatar }}" alt="">
						</a>
						<div class="media-body">
							<h4 class="media-heading">{{ post.author.user.first_name }} {{ post.author.user.last_name }}</h4>
							<p>{{ post.author.bio }}</p>
							<div class="blog-socials">
								<ul>
									<li><a href="{{ post.author.facebook }}"><i class="fa fa-facebook"></i></a></li>
									<li><a href="{{ post.author.twitter }}"><i class="fa fa-twitter"></i></a></li>
									<li><a href="{{ post.author.google }}"><i class="fa fa-google-plus"></i></a></li>
								</ul>
								<a class="btn btn-primary" href="{% url 'blog:author' post.author.pk %}">Other Posts</a>
							</div>
						</div>
					</div><!--Comments-->
					<div class="response-area">
						<h2>{{ count_comments }} RESPONSES</h2>
						<ul class="media-list">
						{% for comment in comments %}
							<li class="media">							
								<a class="pull-left" href="#">
									<img class="media-object" src="{% static 'images/blog/man-two.jpg' %}" alt="">
								</a>
								<div class="media-body">
									<ul class="sinlge-post-meta">
										<li><i class="fa fa-user"></i>{{ comment.author }}</li>
										<li><i class="fa fa-clock-o"></i> {{ comment.created.time }}</li>
										<li><i class="fa fa-calendar"></i>{{ comment.created.date }}</li>
									</ul>
									<p>{{ comment.body }}</p>
									<form action="." method="get" name="form1" id="{{ comment.pk }}">
							
									<input  name="parent_id" type="hidden"  value="{{ comment.pk }}">
									
									<span class="btn btn-primary">
									<i class="fa fa-reply"></i><input class="qwe"  type="submit" value="Replay">
									</span>
									</form>
								</div>
							</li>
						
						{% for reply in comment.replies.all %}	
							<li class="media second-media">
								<a class="pull-left" href="#">
									<img class="media-object" src="{% static 'images/blog/man-three.jpg' %}" alt="">
								</a>
								<div class="media-body">
									<ul class="sinlge-post-meta">
										<li><i class="fa fa-user"></i>{{ reply.author }}</li>
										<li><i class="fa fa-clock-o"></i> {{ reply.created.time }}</li>
										<li><i class="fa fa-calendar"></i> {{ reply.created.date }}</li>
									</ul>
									<p> {{ reply.body }}</p>
									<form action="." method="get" name="form1" id="{{ reply.pk }}">
								
									<input  name="parent_id" type="hidden"  id="id{{ reply.pk }}" value="{{ reply.pk }}">					
									<span class="btn btn-primary">
									<i class="fa fa-reply"></i><input class="qwe"  type="submit" value="Replay">
									</span>
									</form>
								</div>
							</li>
						{% endfor %}
						{% endfor %}	
						</ul>					
					</div><!--/Response-area-->
					<a name="replay-box"></a>
					<div id="replay-box" class="replay-box">
						<div class="row">
							<div class="col-sm-4">
								<h2>Leave a replay</h2>
								<form action="." method="post" id="form-comment">
								
								{% csrf_token %}
									<div class="blank-arrow">
										<label>Your Name</label>
									</div>
									<span>*</span>
									{{ comment_form.author }}
									<div class="blank-arrow">
										<label>Email Address</label>
									</div>
									<span>*</span>
									{{ comment_form.email }}
							</div>
							<div class="col-sm-8">
								<div class="text-area">
									<div class="blank-arrow">
										<label>Comment</label>
									</div>
									<span>*</span>
									{{ comment_form.body }}
									<input  name="parent_id" type="hidden" id="parent_id">	
									<input class="btn btn-primary" type="submit" value="post comment">
								</div>
							</div>
								</form>
							</div>
							
						</div>
					</div><!--/Repaly Box-->

					
{% endblock %}

blogapp/templates/blogapp/blog.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Blog {% endblock %}

{% block content %}
						
						<div class="shipping text-center"><!--shipping-->
							<img src="{% static 'images/home/shipping.jpg' %}" alt="" />
						</div><!--/shipping-->
					</div>
				</div>
				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">Latest From our Blog</h2>
						{% for post in posts %}
						<div class="single-blog-post">
							<h3>{{ post.title }}</h3>
							<div class="post-meta">
								<ul>
									<li><i class="fa fa-user"></i> {{ post.author.user.first_name }} {{ post.author.user.last_name }}</li>
									<li><i class="fa fa-clock-o"></i> {{ post.publish.time }}</li>
									<li><i class="fa fa-calendar"></i> {{ post.publish.date }}</li>
								</ul>

								<span>	
										{% for star in post.count_full_stars %}		
										<i class="fa fa-star"></i>
										{% endfor %}
										{% for star in post.count_emp_stars %}
										<i class="fa fa-star-o"></i>
										{% endfor %}			
								</span>
							</div>
							<a href="">
								<img src="{{ media_url }}{{ post.image }}" alt="">
							</a>
							<p>{{ post.content|truncatewords:30|linebreaks }}</p>
							<a  class="btn btn-primary" href="{{ post.get_absolute_url }}">Read More</a>
						</div>
						{% endfor %}
						
						<div class="pagination-area">
							<ul class="pagination">
								{% if posts.has_previous %}
								<li><a href="?page={{ posts.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a></li>
								{% endif %}

								{% for num in posts.paginator.page_range %}
	
									{% if num == posts.number %}
										<li><a href="?page={{ num }} " class="active"> {{ num }} </a></li>
									{% else %}
									
										<li><a href="?page={{ num }} ">{{ num }} </a></li>
									
									{% endif%}
									
								{% endfor %}
								{% if posts.has_next %}	
								<li><a href="?page={{ posts.next_page_number }}"><i class="fa fa-angle-double-right"></i></a></li>
								{% endif %}
							</ul>
						</div>
						
					</div>
				
{% endblock %}